name: Output of a Step
on:
  workflow_dispatch:
  
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      result_from_step1: ${{ steps.step1.outputs.result }}

    steps:
    - name: step1
      id: step1
      run: echo "result=asdfResultValue" >> "$GITHUB_OUTPUT"

    - name: step2
      env:
        result_from_previous: ${{ steps.step1.outputs.result }}
      run: echo "Hello $result_from_previous from job1step2"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    env:
      result_from_previous_job: ${{ needs.job1.outputs.result_from_step1 }}

    steps:
    - name: step3
      run: echo "Hello $result_from_previous_job from job1step2"
      
