name: Output of a Step
on:
  workflow_dispatch:
  
jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
    - name: step1
      id: step1
      run: echo "result=asdfResultValue" >> "$GITHUB_OUTPUT"

    - name: step2
      env:
        result_from_previous: ${{ steps.step1.outputs.result }}
      run: echo "Hello $result_from_previous"
      
