name: Workflow 1 Hello World
on:
  schedule:
    - cron: '0 1 * * 3'
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  job1:
    environment: int
    runs-on: ubuntu-latest

    steps:
    - name: step1
      run: |
        echo "MY_ENV_VAR=myValue" >> $GITHUB_ENV
        echo 'Hello world'

    - name: step2
      run: echo "Hello $MY_ENV_VAR world again"

    - name: printsecret1
      run: echo ${{ secrets.secret1 }}

    - name: printvar1
      run: echo ${{ vars.int_var_1 }}
      
