on:
  schedule:
    - cron: '0 1 * * 3'
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
    - name: step1
      run: echo 'Hello world'

    - name: step2
      run: echo 'Hello world again'
